name: Run tests
on:
  - push
  - pull_request
jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: docker://theasp/clojurescript-nodejs:shadow-cljs
      - uses: actions/checkout@v4
      - name: run tests
        run: "npm install && npm run test"
