name: Run tests
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v1
        with:
          java-version: "11"
      - name: Install clojure
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: "1.12.0.1479"
      - name: Install dependencies
        run: "npm install"
      - name: Run tests
        run: "npm run test"
